--- #YAML:1.0
name: File-Slurp-Tree
version: 1.22
license: perl
distribution_type: module
requires:
  File::Find::Rule: 0
  File::Path: 0
  File::Slurp: 0
recommends: {}
build_requires:
  Test::More: 0
conflicts: {}
provides:
  File::Slurp::Tree:
    file: lib/File/Slurp/Tree.pm
    version: 1.22
generated_by: Module::Build version 0.19
